export const citiesData = [
  { name: 'Каир', country: 'Египет', region: 'Каир' },
  { name: 'Торонто', country: 'Канада', region: 'Онтарио' },
  { name: 'Алматы', country: 'Казахстан', region: 'Алматы' },
  { name: 'Казань', country: 'Россия', region: 'Татарстан' },
  { name: 'Осака', country: 'Япония', region: 'Осака' },
  { name: 'Йоханнесбург', country: 'ЮАР', region: 'Гаутенг' },
  { name: 'Минск', country: 'Беларусь', region: 'Минская область' },
  { name: 'Мехико', country: 'Мексика', region: 'Мехико' },
  { name: 'Шэньчжэнь', country: 'Китай', region: 'Гуандун' },
  { name: 'Стамбул', country: 'Турция', region: 'Стамбул' },
  { name: 'Москва', country: 'Россия', region: 'Москва' },
  { name: 'Кейптаун', country: 'ЮАР', region: 'Западный Кейп' },
  { name: 'Токио', country: 'Япония', region: 'Токио' },
  { name: 'Гомель', country: 'Беларусь', region: 'Гомельская область' },
  { name: 'Чикаго', country: 'США', region: 'Иллинойс' },
  { name: 'Пекин', country: 'Китай', region: 'Пекин' },
  { name: 'Анкара', country: 'Турция', region: 'Анкара' },
  { name: 'Ванкувер', country: 'Канада', region: 'Британская Колумбия' },
  { name: 'Сальто', country: 'Уругвай', region: 'Сальто' },
  { name: 'Шымкент', country: 'Казахстан', region: 'Шымкент' },
  { name: 'Санкт-Петербург', country: 'Россия', region: 'Санкт-Петербург' },
  { name: 'Монтеррей', country: 'Мексика', region: 'Нуэво-Леон' },
  { name: 'Нагоя', country: 'Япония', region: 'Айти' },
  { name: 'Александрия', country: 'Египет', region: 'Александрия' },
  { name: 'Гродно', country: 'Беларусь', region: 'Гродненская область' },
  { name: 'Нью-Йорк', country: 'США', region: 'Нью-Йорк' },
  { name: 'Чэнду', country: 'Китай', region: 'Сычуань' },
  { name: 'Измир', country: 'Турция', region: 'Измир' },
  { name: 'Монреаль', country: 'Канада', region: 'Квебек' },
  { name: 'Монтевидео', country: 'Уругвай', region: 'Монтевидео' },
  { name: 'Астана', country: 'Казахстан', region: 'Астана' },
  { name: 'Новосибирск', country: 'Россия', region: 'Новосибирская область' },
  { name: 'Гвадалахара', country: 'Мексика', region: 'Халиско' },
  { name: 'Киото', country: 'Япония', region: 'Киото' },
  { name: 'Гиза', country: 'Египет', region: 'Гиза' },
  { name: 'Брест', country: 'Беларусь', region: 'Брестская область' },
  { name: 'Лос-Анджелес', country: 'США', region: 'Калифорния' },
  { name: 'Шанхай', country: 'Китай', region: 'Шанхай' },
  { name: 'Бурса', country: 'Турция', region: 'Бурса' },
  { name: 'Калгари', country: 'Канада', region: 'Альберта' },
  { name: 'Пайсанду', country: 'Уругвай', region: 'Пайсанду' },
  { name: 'Караганда', country: 'Казахстан', region: 'Карагандинская область' },
  { name: 'Екатеринбург', country: 'Россия', region: 'Свердловская область' },
  { name: 'Пуэбла', country: 'Мексика', region: 'Пуэбла' },
  { name: 'Саппоро', country: 'Япония', region: 'Хоккайдо' },
  { name: 'Луксор', country: 'Египет', region: 'Луксор' },
  { name: 'Витебск', country: 'Беларусь', region: 'Витебская область' },
  { name: 'Хьюстон', country: 'США', region: 'Техас' },
  { name: 'Гуанчжоу', country: 'Китай', region: 'Гуандун' },
  { name: 'Анталья', country: 'Турция', region: 'Анталья' },
  { name: 'Оттава', country: 'Канада', region: 'Онтарио' },
  { name: 'Ривера', country: 'Уругвай', region: 'Ривера' },
  { name: 'Актобе', country: 'Казахстан', region: 'Актюбинская область' },
  { name: 'Майами', country: 'США', region: 'Флорида' },
  { name: 'Тихуана', country: 'Мексика', region: 'Нижняя Калифорния' },
  { name: 'Шарм-эш-Шейх', country: 'Египет', region: 'Южный Синай' },
  { name: 'Дурбан', country: 'ЮАР', region: 'Квазулу-Натал' },
  { name: 'Претория', country: 'ЮАР', region: 'Гаутенг' },
  { name: 'Лас-Пьедрас', country: 'Уругвай', region: 'Канелонес' },
  { name: 'Порт-Элизабет', country: 'ЮАР', region: 'Восточный Кейп' },
];
